name: Generate LeetCode Heatmap

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Heatmap
        run: |
          git clone https://github.com/ashutosh00710/leetcode-heatmap.git
          cd leetcode-heatmap
          npm install
          node index.js pragyanshdixit > ../leetcode-heatmap.svg

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add leetcode-heatmap.svg
          git diff --staged --quiet || git commit -m "Update heatmap"
          git push
